apiVersion: v1
type: Opaque
kind: Secret
metadata:
  name: aws-secret
  namespace: longhorn-system
data:
  AWS_ACCESS_KEY_ID: QUtJQVZUVUNTV1RETjVRQUlEVEo=
  AWS_SECRET_ACCESS_KEY: MTdPSXFMR2ROQXlIME1MYWlDTE5QZVUrc25UbHhibWI3MkxmNkR3Qw==