apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: memberlist
  namespace: metallb-system
data:
  secretkey: bUQwL3VoS1kzY21zaXhEZDkvMUxyZlVVYmtEaFFibHYzdkJZOXVia0c3b0Rnamx0UWtldFMwc1VCai9OZGRqcwphU082b0dTNjM5bjdzM0ZGRHZWVzlxamp4NEhFSmRMQlUyWHBPb1JnSDFJQXhsTFVBTEpRNWh6VjhRM3VQOHpnCncrcDM1RUtxVU9XN3N4ZkJlMmJleGlPa2VlOWRhazYxejhSNkcyYWZYNDg9