apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: cert-manager-repo
  values:
    installCRDs: true
  interval: 5m0s
  releaseName: cert-manager
  targetNamespace: cert-manager